import React from "react";
import { Send } from "lucide-react";

const Chat = () => {
  return (
    <div className="flex flex-col h-full bg-white relative">
      {/* Header */}
      <div className="px-6 py-4 border-b border-gray-100 bg-white flex justify-between items-center shadow-sm z-10">
        <div>
          <h2 className="font-bold text-gray-800 text-lg">
            SafeTalk Assistant
          </h2>
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
            <p className="text-xs text-gray-500 font-medium">
              Encrypted & Anonymous
            </p>
          </div>
        </div>
      </div>

      {/* Area Chat */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-slate-50">
        <div className="flex items-start gap-4">
          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-600 to-blue-500 flex items-center justify-center text-white text-sm shadow-md">
            AI
          </div>
          <div className="bg-white p-4 rounded-2xl rounded-tl-none shadow-sm border border-gray-100 max-w-[85%] text-gray-700 leading-relaxed">
            <p>Halo! Saya SafeTalk AI.</p>
            <p className="mt-2">
              Semua percakapan kita dienkripsi end-to-end. Tidak ada jejak yang
              disimpan. Ada yang bisa saya bantu?
            </p>
          </div>
        </div>

        <div className="flex items-start gap-4 flex-row-reverse">
          <div className="w-10 h-10 rounded-full bg-gray-200 flex items-center justify-center text-xs font-bold text-gray-600">
            YOU
          </div>
          <div className="bg-[#0055A5] text-white p-4 rounded-2xl rounded-tr-none shadow-md max-w-[85%] leading-relaxed">
            Saya mau tanya soal keamanan data di website ini. Apakah chat saya
            dibaca admin?
          </div>
        </div>
      </div>

      {/* --- PERBAIKAN AREA INPUT (Menambah Kontras & Border) --- */}
      {/* Menambahkan bayangan halus ke atas (shadow-[...]) agar terpisah dari area chat */}
      <div className="p-4 bg-white border-t border-gray-200 shadow-[0_-4px_10px_-4px_rgba(0,0,0,0.05)] z-10">
        <div className="w-full mx-auto relative flex items-center gap-3">
          <input
            type="text"
            placeholder="Type a secure message..."
            // Ubah bg menjadi gray-50, tambah border abu-abu dan bayangan internal
            className="flex-1 bg-gray-50 border border-gray-200 shadow-inner focus:bg-white focus:border-blue-500 focus:ring-2 focus:ring-blue-100 rounded-full px-6 py-3 transition-all outline-none text-gray-800 placeholder-gray-500"
          />
          <button className="bg-[#0055A5] hover:bg-blue-700 text-white p-3 rounded-full transition-colors shadow-md hover:shadow-lg flex items-center justify-center">
            <Send size={20} />
          </button>
        </div>
        <p className="text-center text-xs text-gray-500 mt-3">
          Messages are generated by AI and may be inaccurate.
        </p>
      </div>
    </div>
  );
};

export default Chat;
